# Generated by Django 6.1.1 on 2026-09-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='inference_time_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='predicted_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='diseases.disease'),
        ),
    ]
